image: alpine

stages:
  - Lint
  - Test
  - Run
  - Scorer
  - Deploy

before_script:
    - apk update && apk add doxygen && apk add python3

Lint:
  stage: Lint
  image: registry.gitlab.com/mafda/python-linting:latest
  script:
    - python --version
    - python
    - flake8

Parser:
  stage: Test
  script:
    - cd tests
    - python3 TestParser.py

Game:
  stage: Test
  script:
    - cd tests
    - python3 TestGame.py

a_an_example:
  stage: Run
  script:
    - cd src
    - python3 polyhash.py ../data/input_data/a_an_example.in.txt
  artifacts:
    paths:
      - data/output_data/*.txt
    expire_in: 1 week

b_better_hurry:
  stage: Run
  script:
    - cd src
    - python3 polyhash.py ../data/input_data/b_better_hurry.in.txt
  artifacts:
    paths:
      - data/output_data/*.txt
    expire_in: 1 week

c_carousel:
  stage: Run
  script:
    - cd src
    - python3 polyhash.py ../data/input_data/c_carousel.in.txt
  artifacts:
    paths:
      - data/output_data/*.txt
    expire_in: 1 week

d_decorated_houses:
  stage: Run
  script:
    - cd src
    - python3 polyhash.py ../data/input_data/d_decorated_houses.in.txt
  artifacts:
    paths:
      - data/output_data/*.txt
    expire_in: 1 week

e_excellent_weather:
  stage: Run
  script:
    - cd src
    - python3 polyhash.py ../data/input_data/e_excellent_weather.in.txt
  artifacts:
    paths:
      - data/output_data/*.txt
    expire_in: 1 week

f_festive_flyover:
  stage: Run
  script:
    - cd src
    - python3 polyhash.py ../data/input_data/f_festive_flyover.in.txt
  artifacts:
    paths:
      - data/output_data/*.txt
    expire_in: 1 week
  
a_an_example_scorer:
  stage: Scorer
  needs: [a_an_example]
  dependencies:
    - a_an_example
  script:
    - cd src
    - python3 scorer.py ../data/input_data/a_an_example.in.txt ../data/output_data/a_an_example.out.txt

b_better_hurry_scorer:
  stage: Scorer
  needs: [b_better_hurry]
  dependencies:
    - b_better_hurry
  script:
    - cd src
    - python3 scorer.py ../data/input_data/b_better_hurry.in.txt ../data/output_data/b_better_hurry.out.txt

c_carousel_scorer:
  stage: Scorer
  needs: [c_carousel]
  dependencies:
    - c_carousel
  script:
    - cd src
    - python3 scorer.py ../data/input_data/c_carousel.in.txt ../data/output_data/c_carousel.out.txt
    
d_decorated_houses_scorer:
  stage: Scorer
  needs: [d_decorated_houses]
  dependencies:
    - d_decorated_houses
  script:
    - cd src
    - python3 scorer.py ../data/input_data/d_decorated_houses.in.txt ../data/output_data/d_decorated_houses.out.txt

e_excellent_weather_scorer:
  stage: Scorer
  needs: [e_excellent_weather]
  dependencies:
    - e_excellent_weather
  script:
    - cd src
    - python3 scorer.py ../data/input_data/e_excellent_weather.in.txt ../data/output_data/e_excellent_weather.out.txt

f_festive_flyover_scorer:
  stage: Scorer
  needs: [f_festive_flyover]
  dependencies:
    - f_festive_flyover
  script:
    - cd src
    - python3 scorer.py ../data/input_data/f_festive_flyover.in.txt ../data/output_data/f_festive_flyover.out.txt

pages:
  stage: Deploy
  script:
    - doxygen docs/Doxyfile
    - mv docs/output/html/ public/
  artifacts:
    paths:
    - public
  only:
    - main
