image: python:latest

before_script:
  - python --version
  - cd tests

stages:
  - Test
  - Run
  - Scorer

Parser:
  stage: Test
  script:
    - python TestParser.py

Game:
  stage: Test
  script:
    - python TestGame.py

a_an_example:
  stage: Run
  script:
    - cd ../src
    - python polyhash.py ../data/input_data/a_an_example.in.txt
  artifacts:
    paths:
      - data/output_data/*.txt
    expire_in: 1 week

a_an_example_scorer:
  stage: Scorer
  needs: [a_an_example]
  dependencies:
    - a_an_example
  script:
    - cd ../src
    - python scorer.py ../data/input_data/a_an_example.in.txt ../data/output_data/a_an_example.out.txt