image: python:latest

before_script:
  - python --version
  - cd tests

stages:
  - Test
  - Run

Parser:
  stage: Test
  script:
    - python TestParser.py

Game:
  stage: Test
  script:
    - python TestGame.py

a_an_example:
  stage: Run
  script:
    - cd ../src
    - python polyhash.py ../data/input_data/a_an_example.in.txt
  artifacts:
    paths:
      - ../data/output_data/*.txt
    expire_in: 1 week
